### ISSUE TITLE
add Greeting github action 

### ISSUE THREAD

**Issue by Yash-Sakre** [Pranav016/Mirage-UI#1]
### Feature request-
This GitHub action greets people who raised an issue.

### Describe the solution you'd like
Create a Greeting.yml file in the .github/workflow folder.

### Describe how this feature will be useful to our readers.
This GitHub action flashes good reflect towards contributors.
<hr/>

Please assign this issue to me as a participant of LGM-SOC'21.

**Comment by Yash-Sakre** [comment]
Please label this issue and assign it to me.

**Comment by Pranav016** [comment]
@Yash-Sakre This repo is not under LGM-SOC. The correct repo you are looking for is this - https://github.com/ALPHAVIO/Mirage-UI
