### ISSUE TITLE
Add wavy background in background folder.

### ISSUE THREAD

**Issue by starrohan999** [Pranav016/Mirage-UI#2]
### Feature request-
can add a wavy background to the landing page.

OUTPUT
![2021-06-11 (8)](https://user-images.githubusercontent.com/71714344/121685229-4cccb780-cadd-11eb-9a59-483fc07e3f8b.png)

#### Are you contributing under any open-source program?

Yes I am LGM SOC  PARTiCIPANT.

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto-assigned.
- It is advised to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull request and add labels accordingly.

**Comment by Pranav016** [comment]
This is the correct repository under lgm-soc https://github.com/ALPHAVIO/Mirage-UI
