### ISSUE TITLE
I would like to add loading animation

### ISSUE THREAD

**Issue by siddhi-244** [Pranav016/Mirage-UI#4]
### Feature request-
I would like to add loading Animation using html,css which can be used as a preloader for any website.

### Describe how this feature will be useful to the users/ contributors-
It can be used as a preloader as well as it can be used while someone is fetching data and it takes time.

#### Are you contributing under any open-source program ?

Psoc

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by siddhi-244** [comment]
I had a doubt in which folder should I add this animation? @Pranav016

**Comment by Pranav016** [comment]
Wrong repo.
Correct repo under PSoC is- https://github.com/ALPHAVIO/Mirage-UI
